### ISSUE TITLE
[FEAT] MainMealView 상의 collection View 구현하기 

### ISSUE THREAD

**Issue by lenamin** [Puhahas/MealOfTheDay#1]
## 📋 Issue
- MainMealView 에 필요한 CollectionView 구현하기 

## 📝  todo
- [ ] 날짜 레이블 구현하기 
- [ ] horizontal collectionView 구현하기 -> 가족 구성원 필터 
- [ ] horizontal collectionView 구현하기 2 -> 가족들의 식사 업로드 사진들 
  -> 하나의 collectionView 안에서 관리하기

- [ ] 식탁 내의 리액션 collectionView 구현 

## 📸 Screenshot

<img width="248" alt="스크린샷 2023-03-13 오후 3 10 51" src="https://user-images.githubusercontent.com/99120199/224621262-313ff0ff-0be8-471b-8046-f7fdf81ca2ac.png">
